# Generated by Django 5.1.7 on 2025-03-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file_content',
            field=models.FileField(upload_to='user_files/'),
        ),
    ]
